db "memory_type", 0
db "pllm_input_divider", 0
db "pllm_feedback_divider", 0
db "pllm_stable_time", 0
db "pllm_setup_control", 0
db "pllm_post_divider", 0
db "pllm_kcp", 0
db "pllm_kvco", 0
db "emc_bct_spare0", 0
db "emc_bct_spare1", 0
db "emc_bct_spare2", 0
db "emc_bct_spare3", 0
db "emc_bct_spare4", 0
db "emc_bct_spare5", 0
db "emc_bct_spare6", 0
db "emc_bct_spare7", 0
db "emc_bct_spare8", 0
db "emc_bct_spare9", 0
db "emc_bct_spare10", 0
db "emc_bct_spare11", 0
db "emc_bct_spare12", 0
db "emc_bct_spare13", 0
db "emc_bct_spare_secure0", 0
db "emc_bct_spare_secure1", 0
db "emc_bct_spare_secure2", 0
db "emc_bct_spare_secure3", 0
db "emc_bct_spare_secure4", 0
db "emc_bct_spare_secure5", 0
db "emc_bct_spare_secure6", 0
db "emc_bct_spare_secure7", 0
db "emc_bct_spare_secure8", 0
db "emc_bct_spare_secure9", 0
db "emc_bct_spare_secure10", 0
db "emc_bct_spare_secure11", 0
db "emc_bct_spare_secure12", 0
db "emc_bct_spare_secure13", 0
db "emc_bct_spare_secure14", 0
db "emc_bct_spare_secure15", 0
db "emc_bct_spare_secure16", 0
db "emc_bct_spare_secure17", 0
db "emc_bct_spare_secure18", 0
db "emc_bct_spare_secure19", 0
db "emc_bct_spare_secure20", 0
db "emc_bct_spare_secure21", 0
db "emc_bct_spare_secure22", 0
db "emc_bct_spare_secure23", 0
db "emc_clock_source", 0
db "emc_clock_source_dll", 0
db "clk_rst_pllm_misc20_override", 0
db "clk_rst_pllm_misc20_override_enable", 0
db "clear_clock2_mc1", 0
db "emc_auto_cal_interval", 0
db "emc_auto_cal_config", 0
db "emc_auto_cal_config2", 0
db "emc_auto_cal_config3", 0
db "emc_auto_cal_config4", 0
db "emc_auto_cal_config5", 0
db "emc_auto_cal_config6", 0
db "emc_auto_cal_config7", 0
db "emc_auto_cal_config8", 0
db "emc_auto_cal_config9", 0
db "emc_auto_cal_vref_sel0", 0
db "emc_auto_cal_vref_sel1", 0
db "emc_auto_cal_channel", 0
db "emc_pmacro_auto_cal_cfg0", 0
db "emc_pmacro_auto_cal_cfg1", 0
db "emc_pmacro_auto_cal_cfg2", 0
db "emc_pmacro_rx_term", 0
db "emc_pmacro_dq_tx_drive", 0
db "emc_pmacro_ca_tx_drive", 0
db "emc_pmacro_cmd_tx_drive", 0
db "emc_pmacro_auto_cal_common", 0
db "emc_pmacro_zcrtl", 0
db "emc_auto_cal_wait", 0
db "emc_xm2_comp_pad_ctrl", 0
db "emc_xm2_comp_pad_ctrl2", 0
db "emc_xm2_comp_pad_ctrl3", 0
db "emc_adr_cfg", 0
db "emc_pin_program_wait", 0
db "emc_pin_extra_wait", 0
db "emc_pin_gpio_enable", 0
db "emc_pin_gpio", 0
db "emc_timing_control_wait", 0
db "emc_rc", 0
db "emc_rfc", 0
db "emc_rfc_pb", 0
db "emc_ref_ctrl2", 0
db "emc_rfc_slr", 0
db "emc_ras", 0
db "emc_rp", 0
db "emc_r2r", 0
db "emc_w2w", 0
db "emc_r2w", 0
db "emc_w2r", 0
db "emc_r2p", 0
db "emc_w2p", 0
db "emc_tppd", 0
db "emc_trtm", 0
db "emc_twtm", 0
db "emc_tratm", 0
db "emc_twatm", 0
db "emc_tr2ref", 0
db "emc_ccdmw", 0
db "emc_rd_rcd", 0
db "emc_wr_rcd", 0
db "emc_rrd", 0
db "emc_rext", 0
db "emc_wext", 0
db "emc_wdv", 0
db "emc_wdv_chk", 0
db "emc_wsv", 0
db "emc_wev", 0
db "emc_wdv_mask", 0
db "emc_ws_duration", 0
db "emc_we_duration", 0
db "emc_quse", 0
db "emc_quse_width", 0
db "emc_ibdly", 0
db "emc_obdly", 0
db "emc_einput", 0
db "emc_einput_duration", 0
db "emc_puterm_extra", 0
db "emc_puterm_width", 0
db "emc_qrst", 0
db "emc_qsafe", 0
db "emc_rdv", 0
db "emc_rdv_mask", 0
db "emc_rdv_early", 0
db "emc_rdv_early_mask", 0
db "emc_qpop", 0
db "emc_refresh", 0
db "emc_burst_refresh_num", 0
db "emc_prerefresh_req_cnt", 0
db "emc_pdex2wr", 0
db "emc_pdex2rd", 0
db "emc_pchg2pden", 0
db "emc_act2pden", 0
db "emc_ar2pden", 0
db "emc_rw2pden", 0
db "emc_cke2pden", 0
db "emc_pdex2che", 0
db "emc_pdex2mrr", 0
db "emc_txsr", 0
db "emc_txsr_dll", 0
db "emc_tcke", 0
db "emc_tckesr", 0
db "emc_tpd", 0
db "emc_tfaw", 0
db "emc_trpab", 0
db "emc_tclkstable", 0
db "emc_tclkstop", 0
db "emc_trefbw", 0
db "emc_fbio_cfg5", 0
db "emc_fbio_cfg7", 0
db "emc_fbio_cfg8", 0
db "emc_cmd_mapping_cmd0_0", 0
db "emc_cmd_mapping_cmd0_1", 0
db "emc_cmd_mapping_cmd0_2", 0
db "emc_cmd_mapping_cmd1_0", 0
db "emc_cmd_mapping_cmd1_1", 0
db "emc_cmd_mapping_cmd1_2", 0
db "emc_cmd_mapping_cmd2_0", 0
db "emc_cmd_mapping_cmd2_1", 0
db "emc_cmd_mapping_cmd2_2", 0
db "emc_cmd_mapping_cmd3_0", 0
db "emc_cmd_mapping_cmd3_1", 0
db "emc_cmd_mapping_cmd3_2", 0
db "emc_cmd_mapping_byte", 0
db "emc_fbio_spare", 0
db "emc_cfg_rsv", 0
db "emc_mrs", 0
db "emc_emrs", 0
db "emc_emrs2", 0
db "emc_emrs3", 0
db "emc_mrw1", 0
db "emc_mrw2", 0
db "emc_mrw3", 0
db "emc_mrw4", 0
db "emc_mrw6", 0
db "emc_mrw8", 0
db "emc_mrw9", 0
db "emc_mrw10", 0
db "emc_mrw12", 0
db "emc_mrw13", 0
db "emc_mrw14", 0
db "emc_mrw_extra", 0
db "emc_warm_boot_mrw_extra", 0
db "emc_warm_boot_extramode_reg_write_enable", 0
db "emc_extramode_reg_write_enable", 0
db "emc_mrw_reset_command", 0
db "emc_mrw_reset_ninit_wait", 0
db "emc_mrs_wait_cnt", 0
db "emc_mrs_wait_cnt2", 0
db "emc_cfg", 0
db "emc_cfg2", 0
db "emc_cfg_pipe", 0
db "emc_cfg_pipe_clk", 0
db "emc_fdpd_ctrl_cmd_no_ramp", 0
db "emc_cfg_update", 0
db "emc_dbg", 0
db "emc_dbg_write_mux", 0
db "emc_cmd_q", 0
db "emc_mc2emc_q", 0
db "emc_dyn_self_ref_control", 0
db "ahb_arbitration_xbar_ctrl_meminit_done", 0
db "emc_cfg_dig_dll", 0
db "emc_cfg_dig_dll_1", 0
db "emc_cfg_dig_dll_period", 0
db "emc_dev_select", 0
db "emc_sel_dpd_ctrl", 0
db "emc_fdpd_ctrl_dq", 0
db "emc_fdpd_ctrl_cmd", 0
db "emc_pmacro_ib_vref_dq_0", 0
db "emc_pmacro_ib_vref_dq_1", 0
db "emc_pmacro_ib_vref_dqs_0", 0
db "emc_pmacro_ib_vref_dqs_1", 0
db "emc_pmacro_ib_rxrt", 0
db "emc_cfg_pipe1", 0
db "emc_cfg_pipe2", 0
db "emc_pmacro_quse_ddll_rank0_0", 0
db "emc_pmacro_quse_ddll_rank0_1", 0
db "emc_pmacro_quse_ddll_rank0_2", 0
db "emc_pmacro_quse_ddll_rank0_3", 0
db "emc_pmacro_quse_ddll_rank0_4", 0
db "emc_pmacro_quse_ddll_rank0_5", 0
db "emc_pmacro_quse_ddll_rank1_0", 0
db "emc_pmacro_quse_ddll_rank1_1", 0
db "emc_pmacro_quse_ddll_rank1_2", 0
db "emc_pmacro_quse_ddll_rank1_3", 0
db "emc_pmacro_quse_ddll_rank1_4", 0
db "emc_pmacro_quse_ddll_rank1_5", 0
db "emc_pmacro_ob_ddll_long_dq_rank0_0", 0
db "emc_pmacro_ob_ddll_long_dq_rank0_1", 0
db "emc_pmacro_ob_ddll_long_dq_rank0_2", 0
db "emc_pmacro_ob_ddll_long_dq_rank0_3", 0
db "emc_pmacro_ob_ddll_long_dq_rank0_4", 0
db "emc_pmacro_ob_ddll_long_dq_rank0_5", 0
db "emc_pmacro_ob_ddll_long_dq_rank1_0", 0
db "emc_pmacro_ob_ddll_long_dq_rank1_1", 0
db "emc_pmacro_ob_ddll_long_dq_rank1_2", 0
db "emc_pmacro_ob_ddll_long_dq_rank1_3", 0
db "emc_pmacro_ob_ddll_long_dq_rank1_4", 0
db "emc_pmacro_ob_ddll_long_dq_rank1_5", 0
db "emc_pmacro_ob_ddll_long_dqs_rank0_0", 0
db "emc_pmacro_ob_ddll_long_dqs_rank0_1", 0
db "emc_pmacro_ob_ddll_long_dqs_rank0_2", 0
db "emc_pmacro_ob_ddll_long_dqs_rank0_3", 0
db "emc_pmacro_ob_ddll_long_dqs_rank0_4", 0
db "emc_pmacro_ob_ddll_long_dqs_rank0_5", 0
db "emc_pmacro_ob_ddll_long_dqs_rank1_0", 0
db "emc_pmacro_ob_ddll_long_dqs_rank1_1", 0
db "emc_pmacro_ob_ddll_long_dqs_rank1_2", 0
db "emc_pmacro_ob_ddll_long_dqs_rank1_3", 0
db "emc_pmacro_ob_ddll_long_dqs_rank1_4", 0
db "emc_pmacro_ob_ddll_long_dqs_rank1_5", 0
db "emc_pmacro_ib_ddll_long_dqs_rank0_0", 0
db "emc_pmacro_ib_ddll_long_dqs_rank0_1", 0
db "emc_pmacro_ib_ddll_long_dqs_rank0_2", 0
db "emc_pmacro_ib_ddll_long_dqs_rank0_3", 0
db "emc_pmacro_ib_ddll_long_dqs_rank1_0", 0
db "emc_pmacro_ib_ddll_long_dqs_rank1_1", 0
db "emc_pmacro_ib_ddll_long_dqs_rank1_2", 0
db "emc_pmacro_ib_ddll_long_dqs_rank1_3", 0
db "emc_pmacro_ddll_long_cmd_0", 0
db "emc_pmacro_ddll_long_cmd_1", 0
db "emc_pmacro_ddll_long_cmd_2", 0
db "emc_pmacro_ddll_long_cmd_3", 0
db "emc_pmacro_ddll_long_cmd_4", 0
db "emc_pmacro_ddll_short_cmd_0", 0
db "emc_pmacro_ddll_short_cmd_1", 0
db "emc_pmacro_ddll_short_cmd_2", 0
db "emc_pmacro_ddll_periodic_offset", 0
db "warm_boot_wait", 0
db "emc_odt_write", 0
db "emc_zcal_interval", 0
db "emc_zcal_wait_cnt", 0
db "emc_zcal_mrw_cmd", 0
db "emc_mrs_reset_dll", 0
db "emc_zcal_init_dev0", 0
db "emc_zcal_init_dev1", 0
db "emc_zcal_init_wait", 0
db "emc_zcal_warm_cold_boot_enables", 0
db "emc_mrw_lpddr2zcal_warm_boot", 0
db "emc_zqcal_ddr3_warm_boot", 0
db "emc_zqcal_lpddr4_warm_boot", 0
db "emc_zcal_warm_boot_wait", 0
db "emc_mrs_warm_boot_enable", 0
db "emc_mrs_reset_dll_wait", 0
db "emc_mrs_extra", 0
db "emc_warm_boot_mrs_extra", 0
db "emc_emrs_ddr2_dll_enable", 0
db "emc_mrs_ddr2_dll_reset", 0
db "emc_emrs_ddr2_ocd_calib", 0
db "emc_ddr2_wait", 0
db "emc_clken_override", 0
db "emc_extra_refresh_num", 0
db "emc_clken_override_allwarm_boot", 0
db "mc_clken_override_allwarm_boot", 0
db "emc_cfg_dig_dll_period_warm_boot", 0
db "pmc_vddp_sel", 0
db "pmc_vddp_sel_wait", 0
db "pmc_ddr_cfg", 0
db "pmc_io_dpd3_req", 0
db "pmc_io_dpd3_req_wait", 0
db "pmc_io_dpd4_req_wait", 0
db "pmc_reg_short", 0
db "pmc_no_io_power", 0
db "pmc_ddr_ctrl_wait", 0
db "pmc_ddr_ctrl", 0
db "emc_acpd_control", 0
db "emc_swizzle_rank0_byte0", 0
db "emc_swizzle_rank0_byte1", 0
db "emc_swizzle_rank0_byte2", 0
db "emc_swizzle_rank0_byte3", 0
db "emc_swizzle_rank1_byte0", 0
db "emc_swizzle_rank1_byte1", 0
db "emc_swizzle_rank1_byte2", 0
db "emc_swizzle_rank1_byte3", 0
db "emc_txdsrvttgen", 0
db "emc_data_brlshft0", 0
db "emc_data_brlshft1", 0
db "emc_dqs_brlshft0", 0
db "emc_dqs_brlshft1", 0
db "emc_cmd_brlshft0", 0
db "emc_cmd_brlshft1", 0
db "emc_cmd_brlshft2", 0
db "emc_cmd_brlshft3", 0
db "emc_quse_brlshft0", 0
db "emc_quse_brlshft1", 0
db "emc_quse_brlshft2", 0
db "emc_quse_brlshft3", 0
db "emc_dll_cfg0", 0
db "emc_dll_cfg1", 0
db "emc_pmc_scratch1", 0
db "emc_pmc_scratch2", 0
db "emc_pmc_scratch3", 0
db "emc_pmacro_pad_cfg_ctrl", 0
db "emc_pmacro_vttgen_ctrl0", 0
db "emc_pmacro_vttgen_ctrl1", 0
db "emc_pmacro_vttgen_ctrl2", 0
db "emc_pmacro_dsr_vttgen_ctrl0", 0
db "emc_pmacro_brick_ctrl_rfu1", 0
db "emc_pmacro_cmd_brick_ctrl_fdpd", 0
db "emc_pmacro_brick_ctrl_rfu2", 0
db "emc_pmacro_data_brick_ctrl_fdpd", 0
db "emc_pmacro_bg_bias_ctrl0", 0
db "emc_pmacro_data_pad_rx_ctrl", 0
db "emc_pmacro_cmd_pad_rx_ctrl", 0
db "emc_pmacro_data_rx_term_mode", 0
db "emc_pmacro_cmd_rx_term_mode", 0
db "emc_pmacro_data_pad_tx_ctrl", 0
db "emc_pmacro_cmd_pad_tx_ctrl", 0
db "emc_cfg3", 0
db "emc_pmacro_tx_pwrd0", 0
db "emc_pmacro_tx_pwrd1", 0
db "emc_pmacro_tx_pwrd2", 0
db "emc_pmacro_tx_pwrd3", 0
db "emc_pmacro_tx_pwrd4", 0
db "emc_pmacro_tx_pwrd5", 0
db "emc_config_sample_delay", 0
db "emc_pmacro_brick_mapping0", 0
db "emc_pmacro_brick_mapping1", 0
db "emc_pmacro_brick_mapping2", 0
db "emc_pmacro_tx_sel_clk_src0", 0
db "emc_pmacro_tx_sel_clk_src1", 0
db "emc_pmacro_tx_sel_clk_src2", 0
db "emc_pmacro_tx_sel_clk_src3", 0
db "emc_pmacro_tx_sel_clk_src4", 0
db "emc_pmacro_tx_sel_clk_src5", 0
db "emc_pmacro_perbit_fgcg_ctrl0", 0
db "emc_pmacro_perbit_fgcg_ctrl1", 0
db "emc_pmacro_perbit_fgcg_ctrl2", 0
db "emc_pmacro_perbit_fgcg_ctrl3", 0
db "emc_pmacro_perbit_fgcg_ctrl4", 0
db "emc_pmacro_perbit_fgcg_ctrl5", 0
db "emc_pmacro_perbit_rfu_ctrl0", 0
db "emc_pmacro_perbit_rfu_ctrl1", 0
db "emc_pmacro_perbit_rfu_ctrl2", 0
db "emc_pmacro_perbit_rfu_ctrl3", 0
db "emc_pmacro_perbit_rfu_ctrl4", 0
db "emc_pmacro_perbit_rfu_ctrl5", 0
db "emc_pmacro_perbit_rfu1_ctrl0", 0
db "emc_pmacro_perbit_rfu1_ctrl1", 0
db "emc_pmacro_perbit_rfu1_ctrl2", 0
db "emc_pmacro_perbit_rfu1_ctrl3", 0
db "emc_pmacro_perbit_rfu1_ctrl4", 0
db "emc_pmacro_perbit_rfu1_ctrl5", 0
db "emc_pmacro_data_pi_ctrl", 0
db "emc_pmacro_cmd_pi_ctrl", 0
db "emc_pmacro_ddll_bypass", 0
db "emc_pmacro_ddll_pwrd0", 0
db "emc_pmacro_ddll_pwrd1", 0
db "emc_pmacro_ddll_pwrd2", 0
db "emc_pmacro_cmd_ctrl0", 0
db "emc_pmacro_cmd_ctrl1", 0
db "emc_pmacro_cmd_ctrl2", 0
db "mc_emem_adr_cfg", 0
db "mc_emem_adr_cfg_dev0", 0
db "mc_emem_adr_cfg_dev1", 0
db "mc_emem_adr_cfg_channel_mask", 0
db "mc_emem_adr_cfg_bank_mask0", 0
db "mc_emem_adr_cfg_bank_mask1", 0
db "mc_emem_adr_cfg_bank_mask2", 0
db "mc_emem_cfg", 0
db "mc_emem_arb_cfg", 0
db "mc_emem_arb_outstanding_req", 0
db "emc_emem_arb_refpb_hp_ctrl", 0
db "emc_emem_arb_refpb_bank_ctrl", 0
db "mc_emem_arb_timing_rcd", 0
db "mc_emem_arb_timing_rp", 0
db "mc_emem_arb_timing_rc", 0
db "mc_emem_arb_timing_ras", 0
db "mc_emem_arb_timing_faw", 0
db "mc_emem_arb_timing_rrd", 0
db "mc_emem_arb_timing_rap2pre", 0
db "mc_emem_arb_timing_wap2pre", 0
db "mc_emem_arb_timing_r2r", 0
db "mc_emem_arb_timing_w2w", 0
db "mc_emem_arb_timing_r2w", 0
db "mc_emem_arb_timing_w2r", 0
db "mc_emem_arb_timing_rfcpb", 0
db "mc_emem_arb_da_turns", 0
db "mc_emem_arb_da_covers", 0
db "mc_emem_arb_misc0", 0
db "mc_emem_arb_misc1", 0
db "mc_emem_arb_misc2", 0
db "mc_emem_arb_ring1_throttle", 0
db "mc_emem_arb_override", 0
db "mc_emem_arb_override1", 0
db "mc_emem_arb_rsv", 0
db "mc_da_cfg0", 0
db "mc_emem_arb_timing_ccdmw", 0
db "mc_clken_override", 0
db "mc_stat_control", 0
db "mc_video_protect_bom", 0
db "mc_video_protect_bom_adr_hi", 0
db "mc_video_protect_size_mb", 0
db "mc_video_protect_vpr_override", 0
db "mc_video_protect_vpr_override1", 0
db "mc_video_protect_gpu_override0", 0
db "mc_video_protect_gpu_override1", 0
db "mc_sec_carveout_bom", 0
db "mc_sec_carveout_adr_hi", 0
db "mc_sec_carveout_size_mb", 0
db "mc_video_protect_write_access", 0
db "mc_sec_carveout_protect_write_access", 0
db "mc_generalized_carveout1_bom", 0
db "mc_generalized_carveout1_bom_hi", 0
db "mc_generalized_carveout1_size_128kb", 0
db "mc_generalized_carveout1_access0", 0
db "mc_generalized_carveout1_access1", 0
db "mc_generalized_carveout1_access2", 0
db "mc_generalized_carveout1_access3", 0
db "mc_generalized_carveout1_access4", 0
db "mc_generalized_carveout1_force_internal_access0", 0
db "mc_generalized_carveout1_force_internal_access1", 0
db "mc_generalized_carveout1_force_internal_access2", 0
db "mc_generalized_carveout1_force_internal_access3", 0
db "mc_generalized_carveout1_force_internal_access4", 0
db "mc_generalized_carveout1_cfg0", 0
db "mc_generalized_carveout2_bom", 0
db "mc_generalized_carveout2_bom_hi", 0
db "mc_generalized_carveout2_size_128kb", 0
db "mc_generalized_carveout2_access0", 0
db "mc_generalized_carveout2_access1", 0
db "mc_generalized_carveout2_access2", 0
db "mc_generalized_carveout2_access3", 0
db "mc_generalized_carveout2_access4", 0
db "mc_generalized_carveout2_force_internal_access0", 0
db "mc_generalized_carveout2_force_internal_access1", 0
db "mc_generalized_carveout2_force_internal_access2", 0
db "mc_generalized_carveout2_force_internal_access3", 0
db "mc_generalized_carveout2_force_internal_access4", 0
db "mc_generalized_carveout2_cfg0", 0
db "mc_generalized_carveout3_bom", 0
db "mc_generalized_carveout3_bom_hi", 0
db "mc_generalized_carveout3_size_128kb", 0
db "mc_generalized_carveout3_access0", 0
db "mc_generalized_carveout3_access1", 0
db "mc_generalized_carveout3_access2", 0
db "mc_generalized_carveout3_access3", 0
db "mc_generalized_carveout3_access4", 0
db "mc_generalized_carveout3_force_internal_access0", 0
db "mc_generalized_carveout3_force_internal_access1", 0
db "mc_generalized_carveout3_force_internal_access2", 0
db "mc_generalized_carveout3_force_internal_access3", 0
db "mc_generalized_carveout3_force_internal_access4", 0
db "mc_generalized_carveout3_cfg0", 0
db "mc_generalized_carveout4_bom", 0
db "mc_generalized_carveout4_bom_hi", 0
db "mc_generalized_carveout4_size_128kb", 0
db "mc_generalized_carveout4_access0", 0
db "mc_generalized_carveout4_access1", 0
db "mc_generalized_carveout4_access2", 0
db "mc_generalized_carveout4_access3", 0
db "mc_generalized_carveout4_access4", 0
db "mc_generalized_carveout4_force_internal_access0", 0
db "mc_generalized_carveout4_force_internal_access1", 0
db "mc_generalized_carveout4_force_internal_access2", 0
db "mc_generalized_carveout4_force_internal_access3", 0
db "mc_generalized_carveout4_force_internal_access4", 0
db "mc_generalized_carveout4_cfg0", 0
db "mc_generalized_carveout5_bom", 0
db "mc_generalized_carveout5_bom_hi", 0
db "mc_generalized_carveout5_size_128kb", 0
db "mc_generalized_carveout5_access0", 0
db "mc_generalized_carveout5_access1", 0
db "mc_generalized_carveout5_access2", 0
db "mc_generalized_carveout5_access3", 0
db "mc_generalized_carveout5_access4", 0
db "mc_generalized_carveout5_force_internal_access0", 0
db "mc_generalized_carveout5_force_internal_access1", 0
db "mc_generalized_carveout5_force_internal_access2", 0
db "mc_generalized_carveout5_force_internal_access3", 0
db "mc_generalized_carveout5_force_internal_access4", 0
db "mc_generalized_carveout5_cfg0", 0
db "emc_ca_training_enable", 0
db "swizzle_rank_byte_encode", 0
db "boot_rom_patch_control", 0
db "boot_rom_patch_data", 0
db "mc_mts_carveout_bom", 0
db "mc_mts_carveout_adr_hi", 0
db "mc_mts_carveout_size_mb", 0
db "mc_mts_carveout_reg_ctrl", 0
db "mc_untranslated_region_check", 0
db "bct_na", 0
db "end."
